"""create_tata_platform_schema

Revision ID: 319dfcc34608
Revises: 
Create Date: 2026-08-28 22:39:19.639291
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '319dfcc34608'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('email_normalized', sa.String(length=320), nullable=False),
    sa.Column('username', sa.String(length=48), nullable=False),
    sa.Column('username_normalized', sa.String(length=48), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('password_algo', sa.String(length=32), nullable=False),
    sa.Column('password_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_online', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'suspended', 'deactivated', 'deleted')", name='ck_account_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_normalized', name='uq_account_email_normalized'),
    sa.UniqueConstraint('username_normalized', name='uq_account_username_normalized')
    )
    op.create_index(op.f('ix_account_created_at'), 'account', ['created_at'], unique=False)
    op.create_index('ix_account_status_created', 'account', ['status', 'created_at'], unique=False)
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('cover_key', sa.String(length=255), nullable=False),
    sa.Column('min_players', sa.Integer(), server_default='2', nullable=False),
    sa.Column('max_players', sa.Integer(), server_default='4', nullable=False),
    sa.Column('default_entry_coins', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_game_slug')
    )
    op.create_index(op.f('ix_game_created_at'), 'game', ['created_at'], unique=False)
    op.create_table('account_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blocker_id', sa.Integer(), nullable=False),
    sa.Column('blocked_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('blocker_id <> blocked_id', name='ck_block_not_self'),
    sa.ForeignKeyConstraint(['blocked_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='uq_block_pair')
    )
    op.create_index(op.f('ix_account_block_blocked_id'), 'account_block', ['blocked_id'], unique=False)
    op.create_index(op.f('ix_account_block_blocker_id'), 'account_block', ['blocker_id'], unique=False)
    op.create_table('auth_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_session_token_hash')
    )
    op.create_index(op.f('ix_auth_session_account_id'), 'auth_session', ['account_id'], unique=False)
    op.create_index('ix_session_account_expires', 'auth_session', ['account_id', 'expires_at'], unique=False)
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_group', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('direct_key', sa.String(length=64), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_preview', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['account.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('direct_key', name='uq_conversation_direct_key')
    )
    op.create_index(op.f('ix_conversation_created_at'), 'conversation', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversation_created_by_id'), 'conversation', ['created_by_id'], unique=False)
    op.create_index('ix_conversation_last_message', 'conversation', ['last_message_at'], unique=False)
    op.create_table('follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followee_id', sa.Integer(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('follower_id <> followee_id', name='ck_follow_not_self'),
    sa.ForeignKeyConstraint(['followee_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'followee_id', name='uq_follow_pair')
    )
    op.create_index('ix_follow_followee_created', 'follow', ['followee_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_follow_follower_id'), 'follow', ['follower_id'], unique=False)
    op.create_table('friend_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'declined', 'cancelled', 'blocked')", name='ck_friend_request_status'),
    sa.CheckConstraint('sender_id <> receiver_id', name='ck_friend_request_not_self'),
    sa.ForeignKeyConstraint(['receiver_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sender_id', 'receiver_id', name='uq_friend_request_pair')
    )
    op.create_index(op.f('ix_friend_request_created_at'), 'friend_request', ['created_at'], unique=False)
    op.create_index('ix_friend_request_receiver_status', 'friend_request', ['receiver_id', 'status'], unique=False)
    op.create_index(op.f('ix_friend_request_sender_id'), 'friend_request', ['sender_id'], unique=False)
    op.create_table('friendship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_low_id', sa.Integer(), nullable=False),
    sa.Column('account_high_id', sa.Integer(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('account_low_id < account_high_id', name='ck_friendship_ordered'),
    sa.ForeignKeyConstraint(['account_high_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['account_low_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_low_id', 'account_high_id', name='uq_friendship_pair')
    )
    op.create_index(op.f('ix_friendship_account_high_id'), 'friendship', ['account_high_id'], unique=False)
    op.create_index(op.f('ix_friendship_account_low_id'), 'friendship', ['account_low_id'], unique=False)
    op.create_table('game_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_private', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('max_players', sa.Integer(), server_default='4', nullable=False),
    sa.Column('player_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('entry_coins', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open', 'in_progress', 'finished', 'closed')", name='ck_game_room_status'),
    sa.CheckConstraint('max_players >= 2', name='ck_game_room_max_players'),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_game_room_code')
    )
    op.create_index(op.f('ix_game_room_created_at'), 'game_room', ['created_at'], unique=False)
    op.create_index(op.f('ix_game_room_game_id'), 'game_room', ['game_id'], unique=False)
    op.create_index('ix_game_room_game_status', 'game_room', ['game_id', 'status'], unique=False)
    op.create_index(op.f('ix_game_room_host_id'), 'game_room', ['host_id'], unique=False)
    op.create_table('player_game_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('matches_played', sa.Integer(), server_default='0', nullable=False),
    sa.Column('wins', sa.Integer(), server_default='0', nullable=False),
    sa.Column('losses', sa.Integer(), server_default='0', nullable=False),
    sa.Column('draws', sa.Integer(), server_default='0', nullable=False),
    sa.Column('best_score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_score', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('current_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('best_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('coins_earned', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('last_played_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'game_id', name='uq_player_game_stat')
    )
    op.create_index(op.f('ix_player_game_stat_account_id'), 'player_game_stat', ['account_id'], unique=False)
    op.create_index(op.f('ix_player_game_stat_created_at'), 'player_game_stat', ['created_at'], unique=False)
    op.create_index(op.f('ix_player_game_stat_game_id'), 'player_game_stat', ['game_id'], unique=False)
    op.create_index('ix_player_game_stat_game_wins', 'player_game_stat', ['game_id', 'wins'], unique=False)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('privacy', sa.String(length=16), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('feeling', sa.String(length=48), nullable=False),
    sa.Column('is_edited', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('reaction_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comment_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('share_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('shared_post_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("privacy IN ('public', 'friends', 'private')", name='ck_post_privacy'),
    sa.ForeignKeyConstraint(['author_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_post_id'], ['post.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_author_created', 'post', ['author_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_post_author_id'), 'post', ['author_id'], unique=False)
    op.create_index(op.f('ix_post_created_at'), 'post', ['created_at'], unique=False)
    op.create_index('ix_post_privacy_created', 'post', ['privacy', 'created_at'], unique=False)
    op.create_index(op.f('ix_post_shared_post_id'), 'post', ['shared_post_id'], unique=False)
    op.create_table('preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('theme', sa.String(length=8), nullable=False),
    sa.Column('profile_visibility', sa.String(length=16), nullable=False),
    sa.Column('show_online_status', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('allow_friend_requests', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('allow_messages_from_strangers', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notify_reactions', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notify_comments', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notify_messages', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notify_friend_requests', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notify_game_invites', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("language IN ('en', 'es', 'fr', 'de', 'pt', 'ar', 'hi')", name='ck_preference_language'),
    sa.CheckConstraint("profile_visibility IN ('public', 'friends', 'private')", name='ck_preference_visibility'),
    sa.CheckConstraint("theme IN ('light', 'dark', 'system')", name='ck_preference_theme'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', name='uq_preference_account')
    )
    op.create_index(op.f('ix_preference_account_id'), 'preference', ['account_id'], unique=False)
    op.create_index(op.f('ix_preference_created_at'), 'preference', ['created_at'], unique=False)
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=False),
    sa.Column('avatar_key', sa.String(length=255), nullable=False),
    sa.Column('cover_key', sa.String(length=255), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('default_post_privacy', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("default_post_privacy IN ('public', 'friends', 'private')", name='ck_profile_default_privacy'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', name='uq_profile_account')
    )
    op.create_index(op.f('ix_profile_account_id'), 'profile', ['account_id'], unique=False)
    op.create_index(op.f('ix_profile_created_at'), 'profile', ['created_at'], unique=False)
    op.create_table('story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('background_color', sa.String(length=16), nullable=False),
    sa.Column('privacy', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('view_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reaction_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reply_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("privacy IN ('public', 'friends', 'private')", name='ck_story_privacy'),
    sa.ForeignKeyConstraint(['author_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_story_author_expires', 'story', ['author_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_story_author_id'), 'story', ['author_id'], unique=False)
    op.create_index(op.f('ix_story_created_at'), 'story', ['created_at'], unique=False)
    op.create_index('ix_story_expires_at', 'story', ['expires_at'], unique=False)
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('balance_coins', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('lifetime_earned_coins', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('lifetime_spent_coins', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('last_daily_reward_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_locked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('balance_coins >= 0', name='ck_wallet_balance_non_negative'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', name='uq_wallet_account')
    )
    op.create_index(op.f('ix_wallet_account_id'), 'wallet', ['account_id'], unique=False)
    op.create_index(op.f('ix_wallet_created_at'), 'wallet', ['created_at'], unique=False)
    op.create_table('coin_ledger_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('amount_coins', sa.BigInteger(), nullable=False),
    sa.Column('balance_after', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('related_room_id', sa.Integer(), nullable=True),
    sa.Column('related_account_id', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("reason IN ('signup_bonus', 'daily_reward', 'game_win', 'game_entry', 'gift_sent', 'gift_received', 'achievement', 'admin_adjustment')", name='ck_coin_ledger_reason'),
    sa.CheckConstraint('amount_coins <> 0', name='ck_coin_ledger_amount_nonzero'),
    sa.CheckConstraint('balance_after >= 0', name='ck_coin_ledger_balance_non_negative'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_account_id'], ['account.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_room_id'], ['game_room.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_coin_ledger_idempotency')
    )
    op.create_index(op.f('ix_coin_ledger_entry_account_id'), 'coin_ledger_entry', ['account_id'], unique=False)
    op.create_index(op.f('ix_coin_ledger_entry_wallet_id'), 'coin_ledger_entry', ['wallet_id'], unique=False)
    op.create_index('ix_coin_ledger_wallet_created', 'coin_ledger_entry', ['wallet_id', 'created_at'], unique=False)
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('depth', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reaction_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reply_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_edited', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_author_id'), 'comment', ['author_id'], unique=False)
    op.create_index(op.f('ix_comment_created_at'), 'comment', ['created_at'], unique=False)
    op.create_index('ix_comment_parent_created', 'comment', ['parent_id', 'created_at'], unique=False)
    op.create_index('ix_comment_post_created', 'comment', ['post_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_comment_post_id'), 'comment', ['post_id'], unique=False)
    op.create_table('game_room_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['game_room.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_room_event_account_id'), 'game_room_event', ['account_id'], unique=False)
    op.create_index(op.f('ix_game_room_event_room_id'), 'game_room_event', ['room_id'], unique=False)
    op.create_index('ix_room_event_room_created', 'game_room_event', ['room_id', 'created_at'], unique=False)
    op.create_table('game_room_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('seat', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_host', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_ready', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['game_room.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'account_id', name='uq_room_member_once')
    )
    op.create_index(op.f('ix_game_room_member_room_id'), 'game_room_member', ['room_id'], unique=False)
    op.create_index('ix_room_member_account', 'game_room_member', ['account_id', 'joined_at'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('reply_to_id', sa.Integer(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('text', 'image', 'video', 'audio', 'file', 'system')", name='ck_message_kind'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to_id'], ['message.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_conversation_created', 'message', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_message_conversation_id'), 'message', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_message_created_at'), 'message', ['created_at'], unique=False)
    op.create_index(op.f('ix_message_sender_id'), 'message', ['sender_id'], unique=False)
    op.create_table('post_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('width', sa.Integer(), server_default='0', nullable=False),
    sa.Column('height', sa.Integer(), server_default='0', nullable=False),
    sa.Column('duration_seconds', sa.Integer(), server_default='0', nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('image', 'video', 'audio', 'file')", name='ck_post_media_kind'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_media_post_id'), 'post_media', ['post_id'], unique=False)
    op.create_index('ix_post_media_post_position', 'post_media', ['post_id', 'position'], unique=False)
    op.create_table('post_reaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('like', 'love', 'haha', 'wow', 'sad', 'angry', 'fire')", name='ck_post_reaction_kind'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'account_id', name='uq_post_reaction_once')
    )
    op.create_index('ix_post_reaction_account', 'post_reaction', ['account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_post_reaction_post_id'), 'post_reaction', ['post_id'], unique=False)
    op.create_table('post_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('privacy', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("privacy IN ('public', 'friends', 'private')", name='ck_post_share_privacy'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_share_account_created', 'post_share', ['account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_post_share_post_id'), 'post_share', ['post_id'], unique=False)
    op.create_table('story_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('width', sa.Integer(), server_default='0', nullable=False),
    sa.Column('height', sa.Integer(), server_default='0', nullable=False),
    sa.Column('duration_seconds', sa.Integer(), server_default='0', nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('image', 'video', 'audio', 'file')", name='ck_story_media_kind'),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_media_story_id'), 'story_media', ['story_id'], unique=False)
    op.create_index('ix_story_media_story_position', 'story_media', ['story_id', 'position'], unique=False)
    op.create_table('story_reaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('like', 'love', 'haha', 'wow', 'sad', 'angry', 'fire')", name='ck_story_reaction_kind'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'account_id', name='uq_story_reaction_once')
    )
    op.create_index(op.f('ix_story_reaction_account_id'), 'story_reaction', ['account_id'], unique=False)
    op.create_index(op.f('ix_story_reaction_story_id'), 'story_reaction', ['story_id'], unique=False)
    op.create_table('story_reply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_reply_author_id'), 'story_reply', ['author_id'], unique=False)
    op.create_index('ix_story_reply_story_created', 'story_reply', ['story_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_story_reply_story_id'), 'story_reply', ['story_id'], unique=False)
    op.create_table('story_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'account_id', name='uq_story_view_once')
    )
    op.create_index(op.f('ix_story_view_account_id'), 'story_view', ['account_id'], unique=False)
    op.create_index(op.f('ix_story_view_story_id'), 'story_view', ['story_id'], unique=False)
    op.create_table('comment_reaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('like', 'love', 'haha', 'wow', 'sad', 'angry', 'fire')", name='ck_comment_reaction_kind'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'account_id', name='uq_comment_reaction_once')
    )
    op.create_index(op.f('ix_comment_reaction_account_id'), 'comment_reaction', ['account_id'], unique=False)
    op.create_index(op.f('ix_comment_reaction_comment_id'), 'comment_reaction', ['comment_id'], unique=False)
    op.create_table('conversation_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('unread_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_read_message_id', sa.Integer(), nullable=True),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_typing', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('typing_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_muted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_read_message_id'], ['message.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'account_id', name='uq_participant_once')
    )
    op.create_index(op.f('ix_conversation_participant_conversation_id'), 'conversation_participant', ['conversation_id'], unique=False)
    op.create_index('ix_participant_account_conv', 'conversation_participant', ['account_id', 'conversation_id'], unique=False)
    op.create_table('message_receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'account_id', name='uq_message_receipt_once')
    )
    op.create_index('ix_message_receipt_account', 'message_receipt', ['account_id', 'read_at'], unique=False)
    op.create_index(op.f('ix_message_receipt_message_id'), 'message_receipt', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_receipt_message_id'), table_name='message_receipt')
    op.drop_index('ix_message_receipt_account', table_name='message_receipt')
    op.drop_table('message_receipt')
    op.drop_index('ix_participant_account_conv', table_name='conversation_participant')
    op.drop_index(op.f('ix_conversation_participant_conversation_id'), table_name='conversation_participant')
    op.drop_table('conversation_participant')
    op.drop_index(op.f('ix_comment_reaction_comment_id'), table_name='comment_reaction')
    op.drop_index(op.f('ix_comment_reaction_account_id'), table_name='comment_reaction')
    op.drop_table('comment_reaction')
    op.drop_index(op.f('ix_story_view_story_id'), table_name='story_view')
    op.drop_index(op.f('ix_story_view_account_id'), table_name='story_view')
    op.drop_table('story_view')
    op.drop_index(op.f('ix_story_reply_story_id'), table_name='story_reply')
    op.drop_index('ix_story_reply_story_created', table_name='story_reply')
    op.drop_index(op.f('ix_story_reply_author_id'), table_name='story_reply')
    op.drop_table('story_reply')
    op.drop_index(op.f('ix_story_reaction_story_id'), table_name='story_reaction')
    op.drop_index(op.f('ix_story_reaction_account_id'), table_name='story_reaction')
    op.drop_table('story_reaction')
    op.drop_index('ix_story_media_story_position', table_name='story_media')
    op.drop_index(op.f('ix_story_media_story_id'), table_name='story_media')
    op.drop_table('story_media')
    op.drop_index(op.f('ix_post_share_post_id'), table_name='post_share')
    op.drop_index('ix_post_share_account_created', table_name='post_share')
    op.drop_table('post_share')
    op.drop_index(op.f('ix_post_reaction_post_id'), table_name='post_reaction')
    op.drop_index('ix_post_reaction_account', table_name='post_reaction')
    op.drop_table('post_reaction')
    op.drop_index('ix_post_media_post_position', table_name='post_media')
    op.drop_index(op.f('ix_post_media_post_id'), table_name='post_media')
    op.drop_table('post_media')
    op.drop_index(op.f('ix_message_sender_id'), table_name='message')
    op.drop_index(op.f('ix_message_created_at'), table_name='message')
    op.drop_index(op.f('ix_message_conversation_id'), table_name='message')
    op.drop_index('ix_message_conversation_created', table_name='message')
    op.drop_table('message')
    op.drop_index('ix_room_member_account', table_name='game_room_member')
    op.drop_index(op.f('ix_game_room_member_room_id'), table_name='game_room_member')
    op.drop_table('game_room_member')
    op.drop_index('ix_room_event_room_created', table_name='game_room_event')
    op.drop_index(op.f('ix_game_room_event_room_id'), table_name='game_room_event')
    op.drop_index(op.f('ix_game_room_event_account_id'), table_name='game_room_event')
    op.drop_table('game_room_event')
    op.drop_index(op.f('ix_comment_post_id'), table_name='comment')
    op.drop_index('ix_comment_post_created', table_name='comment')
    op.drop_index('ix_comment_parent_created', table_name='comment')
    op.drop_index(op.f('ix_comment_created_at'), table_name='comment')
    op.drop_index(op.f('ix_comment_author_id'), table_name='comment')
    op.drop_table('comment')
    op.drop_index('ix_coin_ledger_wallet_created', table_name='coin_ledger_entry')
    op.drop_index(op.f('ix_coin_ledger_entry_wallet_id'), table_name='coin_ledger_entry')
    op.drop_index(op.f('ix_coin_ledger_entry_account_id'), table_name='coin_ledger_entry')
    op.drop_table('coin_ledger_entry')
    op.drop_index(op.f('ix_wallet_created_at'), table_name='wallet')
    op.drop_index(op.f('ix_wallet_account_id'), table_name='wallet')
    op.drop_table('wallet')
    op.drop_index('ix_story_expires_at', table_name='story')
    op.drop_index(op.f('ix_story_created_at'), table_name='story')
    op.drop_index(op.f('ix_story_author_id'), table_name='story')
    op.drop_index('ix_story_author_expires', table_name='story')
    op.drop_table('story')
    op.drop_index(op.f('ix_profile_created_at'), table_name='profile')
    op.drop_index(op.f('ix_profile_account_id'), table_name='profile')
    op.drop_table('profile')
    op.drop_index(op.f('ix_preference_created_at'), table_name='preference')
    op.drop_index(op.f('ix_preference_account_id'), table_name='preference')
    op.drop_table('preference')
    op.drop_index(op.f('ix_post_shared_post_id'), table_name='post')
    op.drop_index('ix_post_privacy_created', table_name='post')
    op.drop_index(op.f('ix_post_created_at'), table_name='post')
    op.drop_index(op.f('ix_post_author_id'), table_name='post')
    op.drop_index('ix_post_author_created', table_name='post')
    op.drop_table('post')
    op.drop_index('ix_player_game_stat_game_wins', table_name='player_game_stat')
    op.drop_index(op.f('ix_player_game_stat_game_id'), table_name='player_game_stat')
    op.drop_index(op.f('ix_player_game_stat_created_at'), table_name='player_game_stat')
    op.drop_index(op.f('ix_player_game_stat_account_id'), table_name='player_game_stat')
    op.drop_table('player_game_stat')
    op.drop_index(op.f('ix_game_room_host_id'), table_name='game_room')
    op.drop_index('ix_game_room_game_status', table_name='game_room')
    op.drop_index(op.f('ix_game_room_game_id'), table_name='game_room')
    op.drop_index(op.f('ix_game_room_created_at'), table_name='game_room')
    op.drop_table('game_room')
    op.drop_index(op.f('ix_friendship_account_low_id'), table_name='friendship')
    op.drop_index(op.f('ix_friendship_account_high_id'), table_name='friendship')
    op.drop_table('friendship')
    op.drop_index(op.f('ix_friend_request_sender_id'), table_name='friend_request')
    op.drop_index('ix_friend_request_receiver_status', table_name='friend_request')
    op.drop_index(op.f('ix_friend_request_created_at'), table_name='friend_request')
    op.drop_table('friend_request')
    op.drop_index(op.f('ix_follow_follower_id'), table_name='follow')
    op.drop_index('ix_follow_followee_created', table_name='follow')
    op.drop_table('follow')
    op.drop_index('ix_conversation_last_message', table_name='conversation')
    op.drop_index(op.f('ix_conversation_created_by_id'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_created_at'), table_name='conversation')
    op.drop_table('conversation')
    op.drop_index('ix_session_account_expires', table_name='auth_session')
    op.drop_index(op.f('ix_auth_session_account_id'), table_name='auth_session')
    op.drop_table('auth_session')
    op.drop_index(op.f('ix_account_block_blocker_id'), table_name='account_block')
    op.drop_index(op.f('ix_account_block_blocked_id'), table_name='account_block')
    op.drop_table('account_block')
    op.drop_index(op.f('ix_game_created_at'), table_name='game')
    op.drop_table('game')
    op.drop_index('ix_account_status_created', table_name='account')
    op.drop_index(op.f('ix_account_created_at'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
