"""add_multiplayer_game_state

Revision ID: 456008a271fb
Revises: 319dfcc34608
Create Date: 2026-09-03 20:46:51.560197
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '456008a271fb'
down_revision: Union[str, Sequence[str], None] = '319dfcc34608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bingo_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('card_index', sa.Integer(), nullable=False),
    sa.Column('grid_json', sa.Text(), server_default='[]', nullable=False),
    sa.Column('marked_json', sa.Text(), server_default='[]', nullable=False),
    sa.Column('marked_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('row_progress_json', sa.Text(), server_default='[0, 0, 0]', nullable=False),
    sa.Column('price_coins', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('claimed_quine', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('claimed_quine_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_double_quine', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('claimed_double_quine_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_full_house', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('claimed_full_house_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_void', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('card_index >= 1 AND card_index <= 10', name='ck_bingo_card_index_range'),
    sa.CheckConstraint('marked_count >= 0', name='ck_bingo_card_marked_non_negative'),
    sa.CheckConstraint('price_coins >= 0', name='ck_bingo_card_price_non_negative'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['game_room.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'account_id', 'card_index', name='uq_bingo_card_room_account_index')
    )
    op.create_index('ix_bingo_card_account_created', 'bingo_card', ['account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_bingo_card_account_id'), 'bingo_card', ['account_id'], unique=False)
    op.create_index('ix_bingo_card_room_account', 'bingo_card', ['room_id', 'account_id'], unique=False)
    op.create_index(op.f('ix_bingo_card_room_id'), 'bingo_card', ['room_id'], unique=False)
    op.create_table('game_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.Text(), server_default='{}', nullable=False),
    sa.Column('state_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sequence', sa.Integer(), server_default='0', nullable=False),
    sa.Column('round_number', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('join', 'leave', 'ready', 'start', 'buy_card', 'draw', 'mark', 'claim_quine', 'claim_double_quine', 'claim_full_house', 'place_tile', 'draw_tile', 'pass_turn', 'roll_dice', 'move_piece', 'capture', 'draw_line', 'close_box', 'discard', 'meld', 'shoot', 'pot_ball', 'foul', 'timeout', 'resign', 'round_end', 'settle', 'reaction', 'system')", name='ck_game_action_kind'),
    sa.CheckConstraint('sequence >= 0', name='ck_game_action_sequence'),
    sa.CheckConstraint('state_version >= 0', name='ck_game_action_state_version'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['game_room.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'sequence', name='uq_game_action_room_sequence')
    )
    op.create_index('ix_game_action_account_created', 'game_action', ['account_id', 'created_at'], unique=False)
    op.create_index('ix_game_action_room_created', 'game_action', ['room_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_game_action_room_id'), 'game_action', ['room_id'], unique=False)
    op.create_index('ix_game_action_room_version', 'game_action', ['room_id', 'state_version'], unique=False)
    op.create_table('game_reaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('target_account_id', sa.Integer(), nullable=True),
    sa.Column('emoji', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('round_number', sa.Integer(), server_default='0', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['game_room.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_account_id'], ['account.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_game_reaction_account_created', 'game_reaction', ['account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_game_reaction_account_id'), 'game_reaction', ['account_id'], unique=False)
    op.create_index('ix_game_reaction_room_created', 'game_reaction', ['room_id', 'created_at'], unique=False)
    op.create_index('ix_game_reaction_room_expires', 'game_reaction', ['room_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_game_reaction_room_id'), 'game_reaction', ['room_id'], unique=False)
    op.add_column('game_room', sa.Column('rules_json', sa.Text(), server_default='{}', nullable=False))
    op.add_column('game_room', sa.Column('state_json', sa.Text(), server_default='{}', nullable=False))
    op.add_column('game_room', sa.Column('current_turn_account_id', sa.Integer(), nullable=True))
    op.add_column('game_room', sa.Column('turn_deadline_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('game_room', sa.Column('round_number', sa.Integer(), server_default='0', nullable=False))
    op.add_column('game_room', sa.Column('pot_coins', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('game_room', sa.Column('state_version', sa.Integer(), server_default='0', nullable=False))
    op.add_column('game_room', sa.Column('winner_account_id', sa.Integer(), nullable=True))
    op.add_column('game_room', sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_game_room_current_turn', 'game_room', ['current_turn_account_id'], unique=False)
    op.create_index('ix_game_room_status_turn_deadline', 'game_room', ['status', 'turn_deadline_at'], unique=False)
    op.create_index('ix_game_room_winner', 'game_room', ['winner_account_id'], unique=False)
    op.create_foreign_key(None, 'game_room', 'account', ['current_turn_account_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'game_room', 'account', ['winner_account_id'], ['id'], ondelete='SET NULL')
    op.create_check_constraint('ck_game_room_pot_non_negative', 'game_room', 'pot_coins >= 0')
    op.create_check_constraint('ck_game_room_round_number', 'game_room', 'round_number >= 0')
    op.create_check_constraint('ck_game_room_state_version', 'game_room', 'state_version >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_game_room_state_version', 'game_room', type_='check')
    op.drop_constraint('ck_game_room_round_number', 'game_room', type_='check')
    op.drop_constraint('ck_game_room_pot_non_negative', 'game_room', type_='check')
    op.drop_constraint(None, 'game_room', type_='foreignkey')
    op.drop_constraint(None, 'game_room', type_='foreignkey')
    op.drop_index('ix_game_room_winner', table_name='game_room')
    op.drop_index('ix_game_room_status_turn_deadline', table_name='game_room')
    op.drop_index('ix_game_room_current_turn', table_name='game_room')
    op.drop_column('game_room', 'settled_at')
    op.drop_column('game_room', 'winner_account_id')
    op.drop_column('game_room', 'state_version')
    op.drop_column('game_room', 'pot_coins')
    op.drop_column('game_room', 'round_number')
    op.drop_column('game_room', 'turn_deadline_at')
    op.drop_column('game_room', 'current_turn_account_id')
    op.drop_column('game_room', 'state_json')
    op.drop_column('game_room', 'rules_json')
    op.drop_index(op.f('ix_game_reaction_room_id'), table_name='game_reaction')
    op.drop_index('ix_game_reaction_room_expires', table_name='game_reaction')
    op.drop_index('ix_game_reaction_room_created', table_name='game_reaction')
    op.drop_index(op.f('ix_game_reaction_account_id'), table_name='game_reaction')
    op.drop_index('ix_game_reaction_account_created', table_name='game_reaction')
    op.drop_table('game_reaction')
    op.drop_index('ix_game_action_room_version', table_name='game_action')
    op.drop_index(op.f('ix_game_action_room_id'), table_name='game_action')
    op.drop_index('ix_game_action_room_created', table_name='game_action')
    op.drop_index('ix_game_action_account_created', table_name='game_action')
    op.drop_table('game_action')
    op.drop_index(op.f('ix_bingo_card_room_id'), table_name='bingo_card')
    op.drop_index('ix_bingo_card_room_account', table_name='bingo_card')
    op.drop_index(op.f('ix_bingo_card_account_id'), table_name='bingo_card')
    op.drop_index('ix_bingo_card_account_created', table_name='bingo_card')
    op.drop_table('bingo_card')
    # ### end Alembic commands ###
